#
# Docker Compose file for the monokal workstation environment.
#

version: '2'
services:
  env:
    image: monokal/env
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
